#!/usr/bin/env python3
"""Regenerate lua/dashboard_art.lua from a source image using img2art.

    pip install img2art opencv-python numpy
    python scripts/gen_dashboard_art.py <image> [cols] [rows] [colors]

Why this drives img2art's Python API instead of the `img2art` CLI:

  * The CLI's --scale is a single float, but character cells are ~2x taller
    than wide, so a portrait needs a non-uniform x/y scale. We resize to the
    character grid ourselves and pass scale=1.0.
  * --alpha emits alpha-nvim's format. dashboard-nvim can't consume it directly,
    but .val and .opts.hl are exactly the art lines and per-cell byte ranges we
    need, so dashboard.lua reads those two fields.
  * convert() does NOT force with_color when alpha=True -- only the CLI does
    that -- so with_color must be passed explicitly or no highlights are emitted.
  * Braille mode (the default) picks characters by threshold, so dark pixels
    become blank cells that cannot show color. This image is mostly dark, so we
    use mapping mode: one character per pixel, no blank cells.
  * _generate_hl() hardcodes 3*x byte offsets, so every mapping character must
    be 3-byte UTF-8. The block ramp below satisfies that; ASCII would not.
  * In mapping mode _convert_color skips its INTER_LINEAR re-resize, so the
    quantized palette survives into a small set of highlight groups. In braille
    mode that re-resize blends the palette back into hundreds of colors.
"""
import sys
from pathlib import Path

import cv2
import numpy as np
from img2art.utils import convert

RAMP = "░▒▓█"  # sparse -> dense; every char is 3 bytes in UTF-8
ROOT = Path(__file__).resolve().parent.parent
DEST = ROOT / "lua" / "dashboard_art.lua"
BANNER = f"""-- Generated by img2art (https://github.com/Asthestarsfalll/img2art)
-- Regenerate with scripts/{Path(__file__).name}. Do not edit by hand.
-- Emitted in alpha-nvim shape; dashboard.lua consumes .val and .opts.hl directly.

"""


def main() -> None:
    if len(sys.argv) < 2:
        raise SystemExit(__doc__)
    src = sys.argv[1]
    cols = int(sys.argv[2]) if len(sys.argv) > 2 else 56
    rows = int(sys.argv[3]) if len(sys.argv) > 3 else 34
    k = int(sys.argv[4]) if len(sys.argv) > 4 else 20

    cv2.setRNGSeed(42)  # keep the kmeans palette reproducible

    im = cv2.imread(src)
    if im is None:
        raise SystemExit(f"cannot read image: {src}")
    h, w = im.shape[:2]
    # crop to head + shoulders, dropping the tin-sign border and screws
    im = im[int(h * 0.10):int(h * 0.82), int(w * 0.09):int(w * 0.91)]

    # straight to the character grid; `rows` already accounts for cell aspect
    grid = cv2.resize(im, (cols, rows), interpolation=cv2.INTER_AREA)

    # quantize here so the palette is deterministic and maps to few hl groups
    z = np.float32(grid.reshape((-1, 3)))
    crit = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 20, 1.0)
    _, labels, palette = cv2.kmeans(z, k, None, crit, 10, cv2.KMEANS_PP_CENTERS)
    grid = palette.astype(np.uint8)[labels.flatten()].reshape(grid.shape)

    tmp_png = ROOT / "scripts" / ".grid.png"
    tmp_lua = ROOT / "scripts" / ".header.lua"
    cv2.imwrite(str(tmp_png), grid)

    # _convert_mapping assigns the i-th darkest unique gray to mapping[i],
    # so the ramp must be exactly as long as the number of unique grays.
    uni = np.unique(cv2.cvtColor(grid, cv2.COLOR_BGR2GRAY))
    n = len(uni)
    mapping = "".join(RAMP[min(int(i / max(n - 1, 1) * len(RAMP)), len(RAMP) - 1)] for i in range(n))
    assert all(len(c.encode()) == 3 for c in mapping), "ramp chars must be 3-byte UTF-8"

    convert(str(tmp_png), scale=1.0, quant=-1, mapping=mapping, alpha=True,
            with_color=True, save_raw=str(tmp_lua))

    DEST.write_text(BANNER + tmp_lua.read_text(encoding="utf-8"), encoding="utf-8")
    tmp_png.unlink(missing_ok=True)
    tmp_lua.unlink(missing_ok=True)
    print(f"wrote {DEST}  ({cols}x{rows}, {n} colors)")


if __name__ == "__main__":
    main()
